# molex Platform modules

MOLEX_PLATFORM_MODULE_VERSION = 1.0
export MOLEX_PLATFORM_MODULE_VERSION

MOLEX_PLATFORM_MODULE = sonic-platform-otn-molex_$(MOLEX_PLATFORM_MODULE_VERSION)_amd64.deb
$(MOLEX_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-otn
$(MOLEX_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(MOLEX_HALCLIENT_DEB)
$(MOLEX_PLATFORM_MODULE)_PLATFORM = x86_64-ols_ila_2.0-r0

SONIC_DPKG_DEBS += $(MOLEX_PLATFORM_MODULE)
