SONIC_CONFIG_VALIDATION_VERSION = 1.0.0
export SONIC_CONFIG_VALIDATION_VERSION

SONIC_CONFIG_VALIDATION = sonic-config-validation_$(SONIC_CONFIG_VALIDATION_VERSION)_all.deb
$(SONIC_CONFIG_VALIDATION)_SRC_PATH = $(PLATFORM_PATH)/sonic-config-validation

SONIC_DPKG_DEBS += $(SONIC_CONFIG_VALIDATION)
