[program:ocs-ledd]
command=/usr/local/bin/ocs-ledd
priority=15
autostart=false
autorestart=unexpected
stdout_logfile=syslog
stderr_logfile=syslog
startsecs=10
startretries=50
dependent_startup=true
dependent_startup_wait_for=rsyslogd:running
