# OCS LED Daemon package

OCS_LED_DAEMON_VERSION = 1.0.0

export OCS_LED_DAEMON_VERSION

OCS_LED_DAEMON = ocs-led-daemon_$(OCS_LED_DAEMON_VERSION)_all.deb
$(OCS_LED_DAEMON)_SRC_PATH = $(PLATFORM_PATH)/ocs-led-daemon
$(OCS_LED_DAEMON)_DEBS_DEPENDS += $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
$(OCS_LED_DAEMON)_WHEEL_DEPENDS += $(SONIC_PY_COMMON_PY3)
SONIC_DPKG_DEBS += $(OCS_LED_DAEMON)
