ALLIEDVISION_VERSION = 1.0.0
OCSKVM_ALLIEDVISION_DEB = allied-vision-$(ALLIEDVISION_VERSION)-amd64.deb
$(OCSKVM_ALLIEDVISION_DEB)_URL = "https://raw.githubusercontent.com/sonic-molex/sonic-libmlx/refs/heads/ocs/$(OCSKVM_ALLIEDVISION_DEB)"

SONIC_ONLINE_DEBS += $(OCSKVM_ALLIEDVISION_DEB)
