# sonic ocs-kvm one image installer

SONIC_ONE_IMAGE = sonic-ocs-kvm.bin
$(SONIC_ONE_IMAGE)_MACHINE = ocs-kvm
$(SONIC_ONE_IMAGE)_IMAGE_TYPE = onie
# NOTE: Removed $(OCSKVM_PYTHON3_SIX_DEB) and $(OCSKVM_THRIFT_PYTHON3_DEB) - using system packages
$(SONIC_ONE_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR) \
                               $(OCSKVM_HALCLIENT_DEB)
$(SONIC_ONE_IMAGE)_LAZY_INSTALLS += $(OCSKVM_OCSV_PLATFORM_MODULE) \
                                    $(OCSKVM_OCS2RUV_PLATFORM_MODULE)
ifeq ($(INSTALL_DEBUG_TOOLS),y)
$(SONIC_ONE_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_DBG_IMAGES)
$(SONIC_ONE_IMAGE)_DOCKERS += $(filter-out $(patsubst %-$(DBG_IMAGE_MARK).gz,%.gz, $(SONIC_INSTALL_DOCKER_DBG_IMAGES)), $(SONIC_INSTALL_DOCKER_IMAGES))
else
$(SONIC_ONE_IMAGE)_DOCKERS = $(SONIC_INSTALL_DOCKER_IMAGES)
endif
SONIC_INSTALLERS += $(SONIC_ONE_IMAGE)
