# ocs-kvm Platform modules

OCSKVM_OCSV_PLATFORM_MODULE_VERSION = 1.1
OCSKVM_OCS2RUV_PLATFORM_MODULE_VERSION = 1.1

OCSKVM_OCSV_PLATFORM_MODULE = sonic-platform-ocs-kvm-ocs-v_$(OCSKVM_OCSV_PLATFORM_MODULE_VERSION)_amd64.deb
$(OCSKVM_OCSV_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-ocs-kvm
$(OCSKVM_OCSV_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(OCSKVM_HALCLIENT_DEB)
$(OCSKVM_OCSV_PLATFORM_MODULE)_PLATFORM = x86_64-ocs-kvm_x86_64-r0

SONIC_DPKG_DEBS += $(OCSKVM_OCSV_PLATFORM_MODULE)

OCSKVM_OCS2RUV_PLATFORM_MODULE = sonic-platform-ocs-kvm-ocs-2ru-v_$(OCSKVM_OCS2RUV_PLATFORM_MODULE_VERSION)_amd64.deb
$(OCSKVM_OCS2RUV_PLATFORM_MODULE)_PLATFORM = x86_64-ocs-kvm_68x68-r0

# ocs-2ru-v is built alongside ocs-v in the same debian build
$(eval $(call add_extra_package,$(OCSKVM_OCSV_PLATFORM_MODULE),$(OCSKVM_OCS2RUV_PLATFORM_MODULE)))
